### ISSUE TITLE
Game won't start, segfault in shader code

### ISSUE THREAD

**Issue by Tunas1337** [SwagSoftware/Kisak-Strike#17]
The game segfaults on startup and doesn't get past a black screen.
Hopefully relevant portion of log of running `./csgo_linux64 -nobreakpad`:
```
[snip]
INTZ NOT SUPPORTED!
Module /home/tunas/code/Kisak-Strike/game/bin/linux64/stdshader_dbg failed to load! Error: ((null))
Module stdshader_dbg failed to load! Error: ((null))
[RocketUI]Font size (614544)
[RocketUI]Loaded font face Lato (from memory).

 ##### swap interval = 0     swap limit = 1 #####
CClientSteamContext logged on = 1
Game.dll loaded for "Counter-Strike: Global Offensive"
CGameEventManager::AddListener: event 'server_pre_shutdown' unknown.
CGameEventManager::AddListener: event 'game_newmap' unknown.
CGameEventManager::AddListener: event 'finale_start' unknown.
CGameEventManager::AddListener: event 'round_start' unknown.
CGameEventManager::AddListener: event 'round_end' unknown.
CGameEventManager::AddListener: event 'difficulty_changed' unknown.
CGameEventManager::AddListener: event 'player_connect' unknown.
CGameEventManager::AddListener: event 'player_disconnect' unknown.
GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative).
GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/coopmission).
****loading serverbrowser_client.so
fish: “./csgo_linux64 -nobreakpad +mat…” terminated by signal SIGSEGV (Address boundary error)
```

Running it through `gdb`  says the segfault is at:
```
0x00007fffe06343d7 in CShaderManager::GetVertexShader (this=0x7fffe06e4fe0 <s_ShaderManager>, vs=93825120167424, dynIdx=0)
    at /home/tunas/code/Kisak-Strike/Kisak-Strike/materialsystem/shaderapidx9/vertexshaderdx8.cpp:4426
4426            return dxshader;
(gdb) bt
#0  0x00007fffe06343d7 in CShaderManager::GetVertexShader (this=0x7fffe06e4fe0 <s_ShaderManager>, vs=93825120167424, dynIdx=0)
    at /home/tunas/code/Kisak-Strike/Kisak-Strike/materialsystem/shaderapidx9/vertexshaderdx8.cpp:4426
#1  0x00007fffe061adf8 in CShaderAPIDx8::DrawMesh2 (this=0x7fffe06e0480 <g_ShaderAPIDX8>, pMesh=0x7fffe06debe8 <g_MeshMgr+1032>, nCount=<optimized out>, pInstances=<optimized out>, 
    nCompressionType=VERTEX_COMPRESSION_NONE, pCompiledState=<optimized out>, pInfo=0x7fffe06e1cae <g_ShaderAPIDX8+6190>)
    at /home/tunas/code/Kisak-Strike/Kisak-Strike/materialsystem/shaderapidx9/shaderapidx8_global.h:96
#2  0x00007fffe061b599 in CShaderAPIDx8::DrawMesh (pInfo=0x7fffe06e1cae <g_ShaderAPIDX8+6190>, pCompiledState=0x7fffe06e1cb0 <g_ShaderAPIDX8+6192>, nCompressionType=VERTEX_COMPRESSION_NONE, 
    pInstances=0x7fffffff98d0, nCount=1, pMesh=0x7fffe06debe8 <g_MeshMgr+1032>, this=0x7fffe06e0480 <g_ShaderAPIDX8>)
    at /home/tunas/code/Kisak-Strike/Kisak-Strike/materialsystem/shaderapidx9/shaderapidx8.cpp:4827
#3  CShaderAPIDx8::DrawMesh (this=0x7fffe06e0480 <g_ShaderAPIDX8>, pMesh=0x7fffe06debe8 <g_MeshMgr+1032>, nCount=1, pInstances=0x7fffffff98d0, nCompressionType=VERTEX_COMPRESSION_NONE, 
    pCompiledState=0x7fffe06e1cb0 <g_ShaderAPIDX8+6192>, pInfo=0x7fffe06e1cae <g_ShaderAPIDX8+6190>) at /home/tunas/code/Kisak-Strike/Kisak-Strike/materialsystem/shaderapidx9/shaderapidx8.cpp:4786
#4  0x00007fffe06010cd in CBaseMeshDX8::DrawMesh (this=0x7fffe06debe8 <g_MeshMgr+1032>, pVecDiffuseModulation=<optimized out>)
    at /home/tunas/code/Kisak-Strike/Kisak-Strike/public/materialsystem/imaterial.h:118
#5  0x00007fffe05f98ba in CDynamicMeshDX8::DrawInternal (this=0x7fffe06debe8 <g_MeshMgr+1032>, pVecDiffuseModulation=0x0, nFirstIndex=186, nIndexCount=66)
```

Help please kudasai. Thank you.

**Comment by Tunas1337** [comment]
Update: I fixed it by making sure I didn't copy the entire bin/ folder from CS:GO's original assets into my game. Don't know how, don't know why.

**Comment by LWSS** [comment]
> Update: I fixed it by making sure I didn't copy the entire bin/ folder from CS:GO's original assets into my game. Don't know how, don't know why.

Most likely you had an original dll in there that wasn't compatible.
